### ISSUE TITLE
Error On Compilation

### ISSUE THREAD

**Issue by ghost** [justalever/job_board#2]
E

Error:
JobsControllerTest#test_should_update_job:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2018-04-03 06:38:41.199140', '2018-04-03 06:38:41.199140', 298486374)
    

bin/rails test test/controllers/jobs_controller_test.rb:36

E

Error:
JobsControllerTest#test_should_show_job:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2018-04-03 06:38:41.441724', '2018-04-03 06:38:41.441724', 298486374)
    

bin/rails test test/controllers/jobs_controller_test.rb:26

E

Error:
JobsControllerTest#test_should_get_new:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2018-04-03 06:38:41.449266', '2018-04-03 06:38:41.449266', 298486374)
    

bin/rails test test/controllers/jobs_controller_test.rb:13

E

Error:
JobsControllerTest#test_should_destroy_job:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2018-04-03 06:38:41.456997', '2018-04-03 06:38:41.456997', 298486374)
    

bin/rails test test/controllers/jobs_controller_test.rb:41

E

Error:
JobsControllerTest#test_should_get_edit:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2018-04-03 06:38:41.465155', '2018-04-03 06:38:41.465155', 298486374)
    

bin/rails test test/controllers/jobs_controller_test.rb:31

E

Error:
JobsControllerTest#test_should_create_job:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2018-04-03 06:38:41.474543', '2018-04-03 06:38:41.474543', 298486374)
    

bin/rails test test/controllers/jobs_controller_test.rb:18

E

Error:
JobsControllerTest#test_should_get_index:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2018-04-03 06:38:41.485154', '2018-04-03 06:38:41.485154', 298486374)

**Comment by ghost** [comment]
It may help to include a getting started guide within the README file. I just forked the repo and began initializing a local environment. On build, I got the above errors.

I'll continue attempting to work around in the meantime. Thanks! Great repo.

**Comment by justalever** [comment]
Hey there! I have yet to cover tests on any of my series. So most will certainly fail. The readme links to a blog post explaining some things in written form but I really recommend starting out with some of my past tutorials. You can find those on my blog or YouTube channel. I gather you know what you're doing if you are running tests though 🙂. PRs are encouraged if you have the time.

**Comment by ghost** [comment]
Gotcha 👍 in that case, I will just continue by running a local rails server, without running any tests. Thank you 😎

**Comment by justalever** [comment]
Roger that! Closing this in the mean time. Thanks!
